# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\" \n\x0fIdentifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\n\n\x08GetState\"\t\n\x07GetInfo\"\"\n\x08SetState\x12\x16\n\x05state\x18\x01 \x01(\x0e\x32\x07.States\"\x83\x01\n\x05State\x12\x1d\n\x08light_on\x18\x01 \x01(\x0e\x32\x0b.LighStates\x12\"\n\tdoor_lock\x18\x02 \x01(\x0e\x32\x0f.DoorLockStates\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x10\n\x08pressure\x18\x04 \x01(\x02\x12\x10\n\x08humidity\x18\x05 \x01(\x02\"@\n\x04Info\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0b\n\x03mac\x18\x02 \x01(\t\x12\x10\n\x08\x62le_name\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"x\n\rClientMessage\x12\x1c\n\x08get_info\x18\x01 \x01(\x0b\x32\x08.GetInfoH\x00\x12\x1e\n\tset_state\x18\x02 \x01(\x0b\x32\t.SetStateH\x00\x12\x1e\n\tget_state\x18\x03 \x01(\x0b\x32\t.GetStateH\x00\x42\t\n\x07message\"m\n\x12\x43ontrollerResponse\x12\x15\n\x04info\x18\x01 \x01(\x0b\x32\x05.InfoH\x00\x12\x17\n\x05state\x18\x02 \x01(\x0b\x32\x06.StateH\x00\x12\x1b\n\x06status\x18\x03 \x01(\x0e\x32\t.StatusesH\x00\x42\n\n\x08response*\x1d\n\x08Statuses\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45rror\x10\x01*\x1d\n\nLighStates\x12\x06\n\x02On\x10\x00\x12\x07\n\x03Off\x10\x01*%\n\x0e\x44oorLockStates\x12\x08\n\x04Open\x10\x00\x12\t\n\x05\x43lose\x10\x01*H\n\x06States\x12\x0b\n\x07LightOn\x10\x00\x12\x0c\n\x08LightOff\x10\x01\x12\x10\n\x0c\x44oorLockOpen\x10\x02\x12\x11\n\rDoorLockClose\x10\x03\x62\x06proto3')



_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSES']._serialized_start=543
  _globals['_STATUSES']._serialized_end=572
  _globals['_LIGHSTATES']._serialized_start=574
  _globals['_LIGHSTATES']._serialized_end=603
  _globals['_DOORLOCKSTATES']._serialized_start=605
  _globals['_DOORLOCKSTATES']._serialized_end=642
  _globals['_STATES']._serialized_start=644
  _globals['_STATES']._serialized_end=716
  _globals['_IDENTIFYREQUEST']._serialized_start=17
  _globals['_IDENTIFYREQUEST']._serialized_end=49
  _globals['_GETSTATE']._serialized_start=51
  _globals['_GETSTATE']._serialized_end=61
  _globals['_GETINFO']._serialized_start=63
  _globals['_GETINFO']._serialized_end=72
  _globals['_SETSTATE']._serialized_start=74
  _globals['_SETSTATE']._serialized_end=108
  _globals['_STATE']._serialized_start=111
  _globals['_STATE']._serialized_end=242
  _globals['_INFO']._serialized_start=244
  _globals['_INFO']._serialized_end=308
  _globals['_CLIENTMESSAGE']._serialized_start=310
  _globals['_CLIENTMESSAGE']._serialized_end=430
  _globals['_CONTROLLERRESPONSE']._serialized_start=432
  _globals['_CONTROLLERRESPONSE']._serialized_end=541
# @@protoc_insertion_point(module_scope)
